### ISSUE TITLE
Roadmap to v2.x

### ISSUE THREAD

**Issue by micooz** [MoePlayer/DPlayer#108]
Here I make an initial task list(no priority order) to show a roadmap to v2.x. We should discuss first then decide what to do next.

- [ ] **build**: refactor webpack configuration and npm scripts.
- [ ] **build**: adapt npm scripts for Windows. #96
- [ ] **benchmark**: add benchmarks to evaluate danmaku performance(load/render/push/clear etc.).
- [ ] **api**: expose seek, show/hide danmaku. #78 
- [ ] **api**: add destroy(). #81 
- [ ] **core**: live mode support. #76 
- [ ] **core**: subtitle support. #100

**Comment by DIYgod** [comment]
- [ ] **core**: segmented mp4 support. [esterTion/flv.js](https://github.com/esterTion/flv.js)
- [ ] **core**: webtorrent support.[webtorrent/webtorrent](https://github.com/webtorrent/webtorrent)
- [ ] **danmaku**: separate danmaku module.
- [ ] **danmaku**: danmaku list.

**Comment by donnes** [comment]
I think it's a good idea to include the implementation of a test framework as goals for v2.x
Good frameworks to take a look:
https://github.com/mochajs/mocha
https://www.npmjs.com/package/tape

**Comment by micooz** [comment]
@donnes 
emmm...I don't think it's possible to include test in v2.x. API changed from time to time, test on unstable or not well-structured code isn't a good practice.

**Comment by donnes** [comment]
So we can starts to creating a Roadmap for v3.x and start writing the new API documentation and development patterns aiming a full code refactoring and testing framework implementation. In my opinion it will made the development more productive and fastest.
Of course in parallel finish the v2.x features.

**Comment by micooz** [comment]
@donnes 
You are right. It's a long term plan.
